spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always